#ifndef GKDOCANDEVICE_GLOBAL_H
#define GKDOCANDEVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GKDOCANDEVICE_LIBRARY)
#  define GKDOCANDEVICE_EXPORT Q_DECL_EXPORT
#else
#  define GKDOCANDEVICE_EXPORT Q_DECL_IMPORT
#endif

#endif // GKDOCANDEVICE_GLOBAL_H
